version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=cleanarch
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    expose:
      - '5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'