spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cleanarch?autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=GMT-3}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: none
    generate-ddl: false
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cleanarch?autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=GMT-3}
    user: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    baseline-on-migrate: true
